
- platform: template
  fans:
    patio_fan:
      friendly_name: "Patio Fan"
      value_template: "{{ states('switch.patio_fan') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.patio_fan
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.patio_fan
    attic_fan:
      friendly_name: "Attic Fan"
      value_template: >
        {% if is_state('switch.quietcool_high', 'on') -%}
        On
        {%- elif is_state('switch.quietcool_low', 'on') -%}
        Low
        {%- else -%}
        Off
        {%- endif %}
      preset_mode_template: "{{ states('input_select.attic_fan_speed') }}"
      turn_on:
        service: script.attic_fan_on
      turn_off:
        service: script.attic_fan_off
      set_preset_mode:
        service: script.attic_fan_set_speed
        data_template:
          preset_mode: "{{ preset_mode }}"
      speed_count: 2
      preset_modes:
        - 'Off'
        - 'Low'
        - 'High'
