- platform: template
  sensors:
    argon_case_temp:
      friendly_name: Argon Case Temperature
      unit_of_measurement: "°F"
      value_template: "{{ state_attr('sensor.argon_one_addon_fan_speed', 'Temperature F') }}"
